import { greeting } from '@/lib/date';

/**
 * What the assistant asks you.
 *
 * Templated for now, and generated by the model later — the screen does not
 * change when that happens, only where the sentence comes from. Starting here
 * means the loop works offline, costs nothing, and cannot fail.
 *
 * Rules the copy follows, and must keep following once a model writes it:
 * never count days, never praise consistency, never guilt an absence. Someone
 * journalling through a hard month should not be told they broke a streak.
 */

interface PromptContext {
  name: string;
  /** Days since the last entry, or null if this is the first. */
  daysSinceLast: number | null;
  hasEntryToday: boolean;
  intention?: string | undefined;
}

const FIRST_TIME = [
  'There is no right way to start. What is on your mind?',
  'What does today feel like so far?',
];

const SAME_DAY = ['Anything else you want to keep from today?', 'Something else on your mind?'];

const RETURNING = [
  'How are you feeling today?',
  'What is today like for you?',
  'What is sitting with you right now?',
  'How has today treated you?',
  'What would you want to remember about today?',
];

const AFTER_A_WHILE = [
  'It has been a little while. How are you?',
  'Whenever you are ready — how have things been?',
];

/**
 * `seed` keeps the question stable for a given day rather than reshuffling on
 * every render, which would feel like the app was fidgeting.
 */
export function dailyPrompt(context: PromptContext, seed = new Date().getDate()): string {
  const pool =
    context.daysSinceLast === null
      ? FIRST_TIME
      : context.hasEntryToday
        ? SAME_DAY
        : context.daysSinceLast >= 7
          ? AFTER_A_WHILE
          : RETURNING;

  return pool[seed % pool.length] ?? RETURNING[0]!;
}

/** "Good morning, Marika" — or just "Good morning" before we know a name. */
export function personalGreeting(name: string, now: Date = new Date()): string {
  const base = greeting(now);
  return name.length > 0 ? `${base}, ${name}` : base;
}
